### ISSUE TITLE
Use Basscss-sass

### ISSUE THREAD

**Issue by borisrorsvort** [johnotander/basscss-rails#3]
Since there is un official sass port. Why not use it as a submodule?
https://github.com/basscss/basscss-sass

**Comment by johnotander** [comment]
I currently have a build script that installs the `basscss-sass` node module and then copies the files over to `app/assets/stylesheets/basscss`. I prefer this route to mucking with submodules in the gemspec (which won't include submodules by default).

I've just added the script to the [Rakefile](https://github.com/johnotander/basscss-rails/blob/master/Rakefile#L4) so that it is now a part of the repo.

**Comment by borisrorsvort** [comment]
:+1:
